spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/gestiondestock
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  ## Specify DBMS
  jpa:
    database: MYSQL
    show-sql: false
    properties:
      hibernate:
        ejb:
          interceptor: com.amos.api.gestiondestock.interceptor.Interceptor
  # Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8001

flickr:
  apiKey: bebb50e36e0a6145192803942a0ff132
  apiSecret: 5bfd53bdc590641b

  appKey : 72157720908082941-7a77afdab0e2f19c
  appSecret : d356a920ebc4341b

